In [ ]:
#candle
#tick
#company data (financial)
#alternate

In [1]:
!pip install yfinance

Requirement already satisfied: yfinance in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (1.4.1)
Requirement already satisfied: pandas>=1.3.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (3.0.3)
Requirement already satisfied: numpy>=1.16.5 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: requests>=2.31 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (2.34.2)
Requirement already satisfied: multitasking>=0.0.7 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (4.10.0)
Requirement already satisfied: pytz>=2022.5 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (2026.2)
Requirement already satisfied: peewee>=3.16.2 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (4.1.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (7.35.1)
Requirement already satisfied: websockets>=13.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Requirement already satisfied: rich in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from requests>=2.31->yfinance) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Users/algo trading 2026/batch 37/.venv/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

In [5]:
import yfinance as yf
df=yf.download(tickers='TSLA',period='10y',multi_level_index=False)
df

[*********************100%***********************]  1 of 1 completed

                 Close        High         Low        Open    Volume
Date
2016-07-05   14.265333   14.302667   13.866667   13.982000  77629500
2016-07-06   14.296000   14.348667   13.933333   14.000000  73798500
2016-07-07   14.396000   14.541333   14.200667   14.206667  54180000
2016-07-08   14.452000   14.654000   14.300000   14.520000  61122000
2016-07-11   14.985333   15.118667   14.634000   14.664000  81447000
...                ...         ...         ...         ...       ...
2026-06-26  379.709991  387.799988  368.600006  370.149994  53434100
2026-06-29  411.839996  413.269989  379.299988  381.790009  57645800
2026-06-30  420.600006  424.540009  406.000000  406.000000  43385600
2026-07-01  425.299988  432.859985  418.089996  421.459991  40127900
2026-07-02  393.450012  432.350006  389.299988  428.010010  73915800

[2513 rows x 5 columns]

In [9]:
data=yf.download(tickers='TSLA',period='2y',interval='1h',multi_level_index=False)
data

[*********************100%***********************]  1 of 1 completed

,Close,High,Low,Open,Volume
Datetime,,,,,
2024-07-03 09:30:00-04:00,244.559998,244.690002,235.440002,235.500000,71003540
2024-07-03 10:30:00-04:00,242.134995,248.350006,241.350800,244.570007,48952000
2024-07-03 11:30:00-04:00,244.970001,246.089996,240.119995,242.134094,25523183
2024-07-05 09:30:00-04:00,246.660004,252.339996,242.470001,252.089905,54276039
2024-07-05 10:30:00-04:00,248.425507,250.570007,245.649994,246.625000,22722967
...,...,...,...,...,...
2026-07-02 11:30:00-04:00,392.929993,400.799988,392.790405,396.929993,8181506
2026-07-02 12:30:00-04:00,391.029999,393.329895,390.079987,392.929993,6737916
2026-07-02 13:30:00-04:00,393.739990,394.450012,389.890015,391.065002,6330886
2026-07-02 14:30:00-04:00,391.209991,394.364990,389.301086,393.649994,5162994
2026-07-02 15:30:00-04:00,392.820007,394.190002,390.910004,391.209991,5476606

In [17]:
data=yf.download(tickers='ETH-USD',period='5d',interval='1m',multi_level_index=False)
data

[*********************100%***********************]  1 of 1 completed

,Close,High,Low,Open,Volume
Datetime,,,,,
2026-06-30 00:00:00+00:00,1609.719971,1610.189941,1609.290039,1610.189941,0
2026-06-30 00:01:00+00:00,1610.010010,1610.410034,1609.479980,1609.959961,9288704
2026-06-30 00:02:00+00:00,1609.689941,1610.439941,1609.619995,1610.089966,0
2026-06-30 00:03:00+00:00,1610.449951,1610.589966,1609.930054,1610.030029,0
2026-06-30 00:04:00+00:00,1611.390015,1611.560059,1609.500000,1609.500000,0
...,...,...,...,...,...
2026-07-04 11:53:00+00:00,1756.400024,1756.500000,1756.140015,1756.500000,0
2026-07-04 11:54:00+00:00,1756.410034,1756.660034,1756.189941,1756.349976,0
2026-07-04 11:55:00+00:00,1756.780029,1756.780029,1756.510010,1756.560059,4891136
2026-07-04 11:56:00+00:00,1756.910034,1757.089966,1756.660034,1756.660034,452397056
2026-07-04 11:57:00+00:00,1757.170044,1757.170044,1757.170044,1757.170044,0

In [18]:
data=yf.download(tickers='ETH-USD',start='2026-06-30',end='2026-07-03',interval='1m',multi_level_index=False)
data

[*********************100%***********************]  1 of 1 completed

,Close,High,Low,Open,Volume
Datetime,,,,,
2026-06-30 00:00:00+00:00,1609.719971,1610.189941,1609.290039,1610.189941,0
2026-06-30 00:01:00+00:00,1610.010010,1610.410034,1609.479980,1609.959961,9288704
2026-06-30 00:02:00+00:00,1609.689941,1610.439941,1609.619995,1610.089966,0
2026-06-30 00:03:00+00:00,1610.449951,1610.589966,1609.930054,1610.030029,0
2026-06-30 00:04:00+00:00,1611.390015,1611.560059,1609.500000,1609.500000,0
...,...,...,...,...,...
2026-07-02 23:54:00+00:00,1698.390015,1698.479980,1697.589966,1697.650024,0
2026-07-02 23:55:00+00:00,1697.859985,1698.459961,1697.689941,1698.250000,3043328
2026-07-02 23:56:00+00:00,1698.459961,1698.589966,1697.989990,1697.989990,0
2026-07-02 23:57:00+00:00,1697.930054,1698.469971,1697.930054,1698.449951,91566080
2026-07-02 23:58:00+00:00,1698.540039,1698.540039,1697.959961,1698.109985,0