In [1]:
import pandas as pd
df=pd.read_csv('/Users/algo trading 2026/batch 37/11_pandas/unicorn.csv')
df

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
0,Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,2012,NaN
1,SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,2002,7.0
2,SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2.0
3,Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2010,2.0
4,Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,2005,4.0
...,...,...,...,...,...,...,...,...,...
1069,Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379.0
1070,Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990.0
1071,Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,2018,80.0
1072,Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0
1073,Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1074 entries, 0 to 1073
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company       1074 non-null   str
 1   Valuation     1074 non-null   int64
 2   Date Joined   1074 non-null   datetime64[us]
 3   Industry      1074 non-null   str
 4   City          1058 non-null   str
 5   Country       1074 non-null   str
 6   Continent     1074 non-null   str
 7   Year Founded  1074 non-null   int64
 8   Funding       1073 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(2), str(5)
memory usage: 75.6 KB

In [4]:
df['Date Joined']=pd.to_datetime(df['Date Joined'],format='%d-%m-%Y')
df

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
0,Bytedance,180,2017-04-07,Artificial intelligence,Beijing,China,Asia,2012,NaN
1,SpaceX,100,2012-12-01,Other,Hawthorne,United States,North America,2002,7.0
2,SHEIN,100,2018-07-03,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2.0
3,Stripe,95,2014-01-23,Fintech,San Francisco,United States,North America,2010,2.0
4,Klarna,46,2011-12-12,Fintech,Stockholm,Sweden,Europe,2005,4.0
...,...,...,...,...,...,...,...,...,...
1069,Zhaogang,1,2017-06-29,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379.0
1070,Zhuan Zhuan,1,2017-04-18,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990.0
1071,Zihaiguo,1,2021-05-06,Consumer & retail,Chongqing,China,Asia,2018,80.0
1072,Zopa,1,2021-10-19,Fintech,London,United Kingdom,Europe,2005,792.0
1073,Zwift,1,2020-09-16,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620.0

In [15]:
start=pd.to_datetime('2022-01-01')
end=pd.to_datetime('2025-12-31')
start,end

(Timestamp('2022-01-01 00:00:00'), Timestamp('2025-12-31 00:00:00'))

In [18]:
df[(df['Date Joined']<end) & (df['Date Joined']>start)]

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
18,Miro,18,2022-01-05,Internet software & services,San Francisco,United States,North America,2011,476.0
117,RELEX Solutions,6,2022-02-17,"Supply chain, logistics, & delivery",Helsinki,Finland,Europe,2005,803.0
163,Qonto,5,2022-01-11,Fintech,Paris,France,Europe,2016,704.0
210,Globalization Partners,4,2022-01-24,Internet software & services,Boston,United States,North America,2012,350.0
220,Hozon Auto,4,2022-02-22,Auto & transportation,Shanghai,China,Asia,2014,2.0
...,...,...,...,...,...,...,...,...,...
1017,Scandit,1,2022-02-09,"Supply chain, logistics, & delivery",Zurich,Switzerland,Europe,2009,273.0
1037,Tarana Wireless,1,2022-03-23,Mobile & telecommunications,Milpitas,United States,North America,2009,376.0
1045,Timescale,1,2022-02-22,Internet software & services,New York,United States,North America,2015,181.0
1053,Veev,1,2022-02-24,Internet software & services,San Mateo,United States,North America,2008,585.0
1059,Watershed,1,2022-02-08,Internet software & services,San Francisco,United States,North America,2019,70.0